version: '3'

services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 11088:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

